# Generated by Django 3.2.5 on 2022-01-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='tags',
        ),
        migrations.AddField(
            model_name='details',
            name='tags',
            field=models.ManyToManyField(to='heart.Tags'),
        ),
    ]
